# =========================
# SPRING_PROFILES_ACTIVE=docker
# =========================
server.port=8081
# Redis
spring.data.redis.host=${REDIS_HOST:redis}
spring.data.redis.port=${REDIS_PORT:6379}

# Keycloak
keycloak.server-url=${KEYCLOAK_URL:http://keycloak:8080}
keycloak.admin.username=${KEYCLOAK_ADMIN_USERNAME:admin}
keycloak.admin.password=${KEYCLOAK_ADMIN_PASSWORD:admin}
keycloak.client-secret=${KEYCLOAK_CLIENT_SECRET}

eureka.client.service-url.defaultZone=http://discovery-service:8761/eureka/