# =========================
# Application - Config commune (tous environnements)
# =========================
spring.application.name=auth-service

server.servlet.context-path=/api/auth

# =========================
# Cache
# =========================
spring.cache.type=redis

# =========================
# Redis - valeurs communes
# =========================
spring.data.redis.database=0
spring.data.redis.timeout=2000ms
spring.data.redis.client-type=lettuce
spring.data.redis.repositories.enabled=false

# =========================
# Keycloak - valeurs communes
# =========================
keycloak.realm=master
keycloak.client-id=auth-service-client

# =========================
# Eureka
# =========================
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true

# =========================
# Swagger
# =========================
springdoc.api-docs.enabled=true
springdoc.api-docs.path=/v3/api-docs