# =========================
# Lancement : ./mvnw spring-boot:run -Dspring-boot.run.profiles=local
# =========================
server.port=8082

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Keycloak
keycloak.server-url=http://localhost:8080
keycloak.admin.username=admin
keycloak.admin.password=admin
keycloak.client-secret=my-secret-value

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/